blank_issues_enabled: false
contact_links:
  - name: ğŸ—¨ï¸ åœ¨çº¿æ–‡æ¡£
    url: http://101.43.53.74:5050/
    about: Admin.NET åœ¨çº¿æ–‡æ¡£
  - name: ğŸš€ åŠŸèƒ½æ¼”ç¤º
    url: http://101.43.53.74:5005/dist/index.html
    about: åœ¨çº¿æ¼”ç¤ºAdmin.NETåŠŸèƒ½